version: '1' # Version 1.0

# services/containers 
services:
  angular:
    build: angular-client # image of the Dockerfile
    ports:
      - "4200:4200" # port

  express: 
    build: express-server # image of the Dockerfile
    ports:
      - "3000:3000" # port
      
  database: 
    image: mongo # image
    ports:
      - "27017:27017" # port